version: "3"
networks:
  projet.net:
    driver: bridge

services:
  # nuxt:
  #   image: node:20
  #   command: sh -c "npm install && npm run dev"
  #   volumes:
  #     - ./:/app
  #   working_dir: /app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   networks:
  #     - projet.net

  db:
    image: "mariadb:latest"
    command: "--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projet
      MYSQL_USER: projet
      MYSQL_PASSWORD: projet
    # volumes:
      # - ./.db_data:/var/lib/mysql
      # - ./sql/data.sql:/docker-entrypoint-initdb.d/datadump.sql
    ports:
      - "3306:3306"
    networks:
      - projet.net

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - projet.net
